platform :ios, '7.0'
target ‘Iguama’ do
    pod 'AFNetworking', '~>2.5.0'
    pod 'JSONModel', '~> 1.0.1'
    pod 'Masonry','~>0.6.1'
    pod 'CocoaLumberjack'
    pod 'ReactiveCocoa', '~> 2.5'
    pod 'SDWebImage', '~> 3.7.5'
    end
